const options = [
   "Stenungsund",
   "Bandar-e Ganāveh", 
   "Burnside", 
   "Parung", 
   "Aranđelovac", 
   "Sawoi", 
   "Daitou", 
   "Nanqiao", 
   "Örnsköldsvik", 
   "Nanterre", 
   "Krajan Dua Dawuan Wetan", 
   "Youssoufia", 
   "Bueng Samakkhi", 
   "Savigny-le-Temple", 
   "Mayqayyng", 
   "Bulacan", 
   "Kermānshāh", 
   "Ḩablah", 
   "Rosario", 
   "Dongbei", 
   "Llano de Piedra", 
   "Karakabak", 
   "Sukoanyar", 
   "Jesús María", 
   "Tanashichō", 
   "Bitaogan", 
   "Yasothon", 
   "Spassk", 
   "Los Angeles", 
   "Jayapura", 
   "Kalisabuk", 
   "Inuyama", 
   "Bertoua", 
   "Zamoskvorech’ye", 
   "Silikatnyy", 
   "Wanling", 
   "Cartagena", 
   "Pelópion", 
   "Cedar Rapids", 
   "Zhongcun", 
   "Caen", 
   "Kuala Lumpur", 
   "Krasnosilka", 
   "Qiaonan", 
   "Shihuang", 
   "Darungan", 
   "San Pedro", 
   "Daliuhao","Metković","Janas"]

  export default options;